### ISSUE TITLE
Concepts build error async_result.hpp

### ISSUE THREAD

**Issue by leleftheriades** [boostorg/asio#312] opened 2019-12-24 11:19 UTC
In **Visual Studio 16.3**
I set the following project property:
**C++ Language Standard:** Preview - Features from the Latest C++ Working Draft (/std:c++latest)

Compilation fails for async_result.hpp

**Comment by 215020267** [comment] 2020-01-02 08:53
We also encountered the same problem.(/std:c++latest)

**Comment by davidstone** [comment] 2020-01-22 17:45
Two things are causing this issue.

The first is that `BOOST_ASIO_CONCEPT` expands to `concept bool` instead of just `concept`. Some compilers also accept this older syntax, but it is not what's in the current draft of the standard.

The second problem is this code from async_result.hpp

```
template <typename T>
BOOST_ASIO_CONCEPT completion_signature =
  detail::is_completion_signature<T>::value;
```
```
template <typename T, completion_signature Signature>
BOOST_ASIO_CONCEPT completion_handler_for =
  detail::is_completion_handler_for<T, Signature>::value;
```

The first snippet is defining a concept. The second is trying to constrain the concept definition on the first concept, which is incorrect. Assuming the logic is otherwise correct, what you need to do here is instead (for the second snippet)

```
template <typename T, typename Signature>
BOOST_ASIO_CONCEPT completion_handler_for =
  completion_signature<Signature> and detail::is_completion_handler_for<T, Signature>::value;
```

Alternatively, `is_completion_handler_for` could be defined to require `completion_signature` for its second parameter.

**Comment by stevefan1999-personal** [comment] 2020-01-23 07:50
Disable MSVC concepts for the time being:
```cmake
if (MSVC)
  add_definitions(-DBOOST_ASIO_DISABLE_CONCEPTS)
endif()
```

**Comment by davidstone** [comment] 2020-01-23 17:24
This does not just affect MSVC. clang trunk fails to compile the code due to the second issue I outlined, and I wouldn't be surprised if gcc trunk will fail, too.

**Comment by tchaikov** [comment] 2020-02-12 07:34
GCC-10 also fails to build. 
```
/opt/ceph/include/boost/asio/async_result.hpp:70:20: error: a variable concept cannot be constrained
   70 | BOOST_ASIO_CONCEPT completion_handler_for =
      |                    ^~~~~~~~~~~~~~~~~~~~~~
/opt/ceph/include/boost/asio/async_result.hpp:492:20: error: a variable concept cannot be constrained
  492 | BOOST_ASIO_CONCEPT completion_token_for = requires(T&& t)
      |                    ^~~~~~~~~~~~~~~~~~~~
```

the reason why it compiles with GCC-9 and before is that `async_result.hpp` is using the bug of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67658 , which was in turn fixed in GCC-10.

**Comment by stevefan1999-personal** [comment] 2020-02-12 13:28
Hmm, it seems like it is a complete semantic change, so not a regression, but more serious than that.

**Comment by MakersF** [comment] 2020-03-24 15:40
I can confirm this fails to compile with clang-11

There is a warning for the old way of specifying a concept

```
/boost_1_72_0/boost/asio/async_result.hpp:70:20: warning: ISO C++20 does not permit the 'bool' keyword after 'concept' [-Wconcepts-ts-compat]
BOOST_ASIO_CONCEPT completion_handler_for =
                   ^
```

and there is an error for constraining the concept

```
/boost_1_72_0/boost/asio/async_result.hpp:70:20: error: concept cannot have associated constraints
```

**Comment by madmongo1** [comment] 2020-03-30 14:08
Related Downstream:  boostorg/beast#1884

**Comment by yumetodo** [comment] 2020-04-26 04:29
I have just faced this issue when I specified `/std:c++latest` to use template syntax for generic lambdas.

**Comment by Philosoph228** [comment] 2020-05-19 04:30
Till we waiting for the next boost release, here is a temporary solution. You can produce a `.patch` file from Chris' commit https://github.com/chriskohlhoff/asio/commit/00157db09efc9ce65e01ea37346a06b3d82d4f65 on upstream repository and replace `ASIO_*` namings to `BOOST_ASIO_*`. Then apply that patch on your existing boost install, as I did.

**Closed** 2020-12-30 01:12 UTC
